/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import Model.DataDescriptor.ChiTietHoaDon;
import Model.DataDescriptor.HoaDon;
import Model.DataDescriptor.Sach;
import Model.InteractData.ChiTietHoaDonDAO;
import Model.InteractData.HoaDonDAO;
import Model.InteractData.KhachHangDAO;
import Model.InteractData.SachDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Admin
 */
public class HoaDonViews1 extends javax.swing.JPanel {

    private ChiTietHoaDonDAO contrCTHD = new ChiTietHoaDonDAO();
    private HoaDonDAO contrHD = new HoaDonDAO();
    private KhachHangDAO contrKH = new KhachHangDAO();
    private SachDAO contrS = new SachDAO();
    
    public HoaDonViews1() {
        initComponents();
        System.out.println("vào hóa đơn");
        LayDuLieuDanhSachHoaDon(contrHD.getHoaDon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTF_IDNV = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTF_IDSach = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jCbb_thangTao = new javax.swing.JComboBox<>();
        jCbb_ngayTao = new javax.swing.JComboBox<>();
        jTF_SoLuong = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTF_SDTKH = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        tb_CTHD1 = new javax.swing.JTable();
        jCbb_namTao = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTF_IDHD = new javax.swing.JTextField();
        jTF_TongTien = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jTF_TimTheoMa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnSearchTK4 = new javax.swing.JButton();
        btnClearTK3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tb_DSHD = new javax.swing.JTable();
        jCbb_ngayBD = new javax.swing.JComboBox<>();
        jCbb_thangBD = new javax.swing.JComboBox<>();
        jCbb_namBD = new javax.swing.JComboBox<>();
        jCbb_ngayKT = new javax.swing.JComboBox<>();
        jCbb_thangKT = new javax.swing.JComboBox<>();
        jCbb_namKT = new javax.swing.JComboBox<>();
        jPanel26 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        tb_CTHD = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1290, 945));

        jTabbedPane2.setBackground(new java.awt.Color(0, 153, 102));
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(1080, 720));

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tạo hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Mã hóa đơn:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("ID Nhân viên:");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("SDT Khách hàng :");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Ngày hóa đơn :");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("Mã sách");

        jTF_IDNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setText("Số lượng ");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setText("Tổng tiền :");

        jTF_IDSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton7.setBackground(new java.awt.Color(0, 255, 51));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setText("Hoàn thành");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jCbb_thangTao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbb_thangTao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jCbb_ngayTao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbb_ngayTao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jTF_SoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTF_SoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_SoLuongActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setText("Xóa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTF_SDTKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Thêm sách");

        tb_CTHD1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tb_CTHD1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Tên sách", "Số lượng"
            }
        ));
        tb_CTHD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_CTHD1MouseClicked(evt);
            }
        });
        jScrollPane15.setViewportView(tb_CTHD1);

        jCbb_namTao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbb_namTao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960" }));

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 153, 51));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setText("Tạo hóa đơn mới");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTF_IDHD.setEditable(false);
        jTF_IDHD.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTF_IDHDComponentAdded(evt);
            }
        });

        jTF_TongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTF_TongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_TongTienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF_IDSach, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel11Layout.createSequentialGroup()
                                                .addGap(103, 103, 103)
                                                .addComponent(jButton8))
                                            .addGroup(jPanel11Layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTF_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(jButton2)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(jButton7)))
                                .addGap(50, 50, 50))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTF_IDHD, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(jTF_IDNV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jCbb_ngayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCbb_thangTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCbb_namTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTF_SDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(282, 282, 282))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_IDHD, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_IDNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbb_ngayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbb_thangTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbb_namTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_SDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_IDSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jTF_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                        .addGap(38, 38, 38))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Tạo hóa đơn", jPanel2);

        jPanel5.setBackground(new java.awt.Color(0, 153, 102));
        jPanel5.setPreferredSize(new java.awt.Dimension(1060, 689));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTF_TimTheoMa.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTF_TimTheoMaCaretUpdate(evt);
            }
        });
        jTF_TimTheoMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_TimTheoMaActionPerformed(evt);
            }
        });
        jTF_TimTheoMa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTF_TimTheoMaKeyReleased(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Ngày bắt đầu:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Ngày kết thúc:");

        btnSearchTK4.setBackground(new java.awt.Color(255, 102, 102));
        btnSearchTK4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchTK4.setText("Tìm kiếm");
        btnSearchTK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTK4ActionPerformed(evt);
            }
        });

        btnClearTK3.setBackground(new java.awt.Color(0, 255, 102));
        btnClearTK3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClearTK3.setText("Làm mới");
        btnClearTK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTK3ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Tìm theo Mã HĐ");

        tb_DSHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tb_DSHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Hóa Đơn", "Mã nhân viên", "Tên khách hàng", "Ngày tạo", "Tổng tiền"
            }
        ));
        tb_DSHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_DSHDMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tb_DSHD);

        jCbb_ngayBD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbb_ngayBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jCbb_thangBD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbb_thangBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jCbb_namBD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbb_namBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960" }));

        jCbb_ngayKT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbb_ngayKT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jCbb_thangKT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbb_thangKT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jCbb_namKT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbb_namKT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960" }));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addComponent(jCbb_ngayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCbb_thangBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jCbb_namBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addComponent(jCbb_ngayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCbb_thangKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jCbb_namKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearchTK4)
                    .addComponent(btnClearTK3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTF_TimTheoMa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(392, Short.MAX_VALUE))
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 1376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCbb_ngayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCbb_thangBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCbb_namBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchTK4))
                    .addComponent(jLabel10)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jCbb_ngayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbb_thangKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbb_namKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnClearTK3))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTF_TimTheoMa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hóa đơn chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tb_CTHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tb_CTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên sách", "Số lượng", "Đơn giá/1 sản phẩm", "Thành tiền"
            }
        ));
        jScrollPane14.setViewportView(tb_CTHD);
        if (tb_CTHD.getColumnModel().getColumnCount() > 0) {
            tb_CTHD.getColumnModel().getColumn(3).setHeaderValue("Đơn giá/1 sản phẩm");
            tb_CTHD.getColumnModel().getColumn(4).setHeaderValue("Thành tiền");
        }

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 1372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Danh sách hóa đơn", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1498, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here: 
        ThongBao("Hoàn thành!", "", 1);
        ResTaoHoaDon(); 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTF_TimTheoMaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTF_TimTheoMaCaretUpdate
        // TODO add your handling code here:
        //
    }//GEN-LAST:event_jTF_TimTheoMaCaretUpdate

    private void btnSearchTK4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTK4ActionPerformed
        
        String NgayBD, NgayKT, ngay, thang, nam;
        ngay = jCbb_ngayBD.getSelectedItem().toString();
        thang = jCbb_thangBD.getSelectedItem().toString();
        nam = jCbb_namBD.getSelectedItem().toString();
        NgayBD  = nam + "-" + thang + "-" + ngay;
        ngay = jCbb_ngayKT.getSelectedItem().toString();
        thang = jCbb_thangKT.getSelectedItem().toString();
        nam = jCbb_namKT.getSelectedItem().toString();
        NgayKT  = nam + "-" + thang + "-" + ngay;
        
        LayDuLieuDanhSachHoaDon(contrHD.getHoaDonTheoThoiGian(NgayBD, NgayKT));
        
    }//GEN-LAST:event_btnSearchTK4ActionPerformed

    private void btnClearTK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTK3ActionPerformed
        LayDuLieuDanhSachHoaDon(contrHD.getHoaDon());
    }//GEN-LAST:event_btnClearTK3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ID_HD, ID_Sach;
        int SoLuong;
        ID_HD = jTF_IDHD.getText();
        ID_Sach = jTF_IDSach.getText();
        SoLuong = Integer.parseInt(jTF_SoLuong.getText());
        Sach sachXoa = contrS.getMotSachID(ID_Sach);
        ChiTietHoaDon a = new ChiTietHoaDon(sachXoa, SoLuong);
        HoaDon hd1 = contrHD.getMotHoaDonTheoID(ID_HD);
        try {
            contrCTHD.deleteChiTietHoaDon(hd1, a);
            LayDuLieuChiTietHoaDon1(contrCTHD.getChiTietHoaDon(ID_HD));
            CapNhatTongTien(ID_HD);
        } catch (SQLException ex) {
            Logger.getLogger(HoaDonViews1.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          
        String ID_Sach, ID_HD;
        int SoLuong;
        ID_HD = jTF_IDHD.getText();
        ID_Sach = jTF_IDSach.getText();
        SoLuong = Integer.parseInt(jTF_SoLuong.getText());
        Sach sachThem = contrS.getMotSachID(ID_Sach);
        ChiTietHoaDon a = new ChiTietHoaDon(sachThem, SoLuong);
        HoaDon hd1 = contrHD.getMotHoaDonTheoID(ID_HD);
        if (SoLuong > sachThem.getSoLuong()){
            ThongBao("Không đủ số lượng Sách!", "", 0);
        }
        else {
            try {
                contrCTHD.addChiTietHoaDon(hd1, a);
                LayDuLieuChiTietHoaDon1(contrCTHD.getChiTietHoaDon(ID_HD));
                CapNhatTongTien(ID_HD);
            } catch (SQLException ex) {
                Logger.getLogger(HoaDonViews1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here: 
        String ID_HD="", ID_NV, SDT, ID_KH="", NgayTao;
        ID_NV = jTF_IDNV.getText();
        SDT = jTF_SDTKH.getText();
        String ngay, thang, nam;
        ngay = jCbb_ngayTao.getSelectedItem().toString();
        thang = jCbb_thangTao.getSelectedItem().toString();
        nam = jCbb_namTao.getSelectedItem().toString();
        NgayTao  = nam + "-" + thang + "-" + ngay;
        
        ID_KH = contrKH.getKHTheoSDT(SDT).getID_KH();
        if (!contrKH.kiemTraKH(SDT)){
            ThongBao("Khách hàng này chưa tồn tại trong CSDL\nVui lòng thêm Khách hàng mới trong mục Khách Hàng!", "", 0);
        }else {
            try {
                contrHD.addHoaDon(ID_KH, ID_NV, NgayTao);
                ThongBao("Tạo Hóa đơn thành công!", "", 1);
                ID_HD = HoaDonDAO.idVuaTao;
                jTF_IDHD.setText(ID_HD); 
                LayDuLieuChiTietHoaDon1(contrCTHD.getChiTietHoaDon(ID_HD));
                CapNhatTongTien(ID_HD); 
            } catch (SQLException ex) {
                Logger.getLogger(HoaDonViews1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tb_DSHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DSHDMouseClicked
       int viTriDongVuaBam = tb_DSHD.getSelectedRow();
        String ID_HD = tb_DSHD.getValueAt(viTriDongVuaBam, 1).toString();
        LayDuLieuChiTietHoaDon(contrCTHD.getChiTietHoaDon(ID_HD));     
    }//GEN-LAST:event_tb_DSHDMouseClicked

    private void jTF_TimTheoMaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_TimTheoMaKeyReleased
        // TODO add your handling code here:   
        LayDuLieuDanhSachHoaDon(contrHD.getHoaDonTheoID(jTF_TimTheoMa.getText()));
        
        
    }//GEN-LAST:event_jTF_TimTheoMaKeyReleased

    private void jTF_TimTheoMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_TimTheoMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_TimTheoMaActionPerformed

    private void jTF_IDHDComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTF_IDHDComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_IDHDComponentAdded

    private void jTF_TongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_TongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_TongTienActionPerformed

    private void jTF_SoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_SoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_SoLuongActionPerformed

    private void tb_CTHD1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_CTHD1MouseClicked
        // TODO add your handling code here:
        int viTriDongVuaBam = tb_CTHD1.getSelectedRow();
        String ID_Sach = tb_CTHD1.getValueAt(viTriDongVuaBam, 0).toString();
        String SoLuong = tb_CTHD1.getValueAt(viTriDongVuaBam, 3).toString();
        
        jTF_IDSach.setText(ID_Sach);
        jTF_SoLuong.setText(SoLuong);
    }//GEN-LAST:event_tb_CTHD1MouseClicked

    public void ThongBao(String noiDungThongBao, String tieuDeThongBao, int icon) {
        JOptionPane.showMessageDialog(new JFrame(), noiDungThongBao,
                tieuDeThongBao, icon);
    }
    
    private void CapNhatTongTien(String ID_HD){
        long tong = contrHD.getMotHoaDonTheoID(ID_HD).getTongTien();
        jTF_TongTien.setText(String.valueOf(tong));
    }
    
    public void ResTaoHoaDon() {
        jTF_IDNV.setText("");
        jTF_SDTKH.setText("");
        jTF_IDHD.setText("");
        jTF_IDSach.setText("");
        jTF_SoLuong.setText("");
        jTF_TongTien.setText("");
        Object[] obj = new Object[]{"ID_Sach", "Tên Sách", "Tác Giả", "Số lượng", "Đơn giá/1 sản phẩm", "Thành Tiền"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tb_CTHD1.setModel(tableModel);
   
    }
    
    public void LayDuLieuChiTietHoaDon1(ArrayList<ChiTietHoaDon> chiTietSach) { 
        Object[] obj = new Object[]{"ID_Sach", "Tên Sách", "Tác Giả", "Số lượng", "Đơn giá/1 sản phẩm", "Thành Tiền"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tb_CTHD1.setModel(tableModel);
        for (ChiTietHoaDon x : chiTietSach){
            Object[] item = new Object[7];
            item[0] = x.getSach().getID_Sach();
            item[1] = x.getSach().getTen();
            item[2] = x.getSach().getTacGia();
            item[3] = x.getSoLuong();
            item[4] = x.getSach().getGiaBan();
            item[5] = x.getThanhTien();
            tableModel.addRow(item);
        }
    }
    
    public void LayDuLieuChiTietHoaDon(ArrayList<ChiTietHoaDon> chiTietSach) { 
        Object[] obj = new Object[]{"STT", "Tên Sách", "Tác Giả", "Số lượng", "Đơn giá/1 sản phẩm", "Thành Tiền"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tb_CTHD.setModel(tableModel);
        int c = 0;
        for (ChiTietHoaDon x : chiTietSach){
            Object[] item = new Object[7];
            c++;
            item[0] = c;
            item[1] = x.getSach().getTen();
            item[2] = x.getSach().getTacGia();
            item[3] = x.getSoLuong();
            item[4] = x.getSach().getGiaBan();
            item[5] = x.getThanhTien();
            tableModel.addRow(item);
        }
    }
    
    public void LayDuLieuDanhSachHoaDon(ArrayList<HoaDon> listHD) { 
        System.out.println("đã lấy danh sách");
        Object[] obj = new Object[]{"STT", "ID Hóa đơn", "ID Nhân Viên ", "Nhân Viên", "Khách hàng", "SDT", "Ngày tạo", "Tổng tiền"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tb_DSHD.setModel(tableModel);
        int c = 0;
        for (HoaDon x : listHD){
            Object[] item = new Object[9];
            c++;
            item[0] = c;
            item[1] = x.getID_HD();
            item[2] = x.getNhanVien().getID_NV();
            item[3] = x.getNhanVien().getTen();
            item[4] = x.getKhachHang().getTen();
            item[5] = x.getKhachHang().getSDT();
            item[6] = x.getNgayXuat();
            item[7] = x.getTongTien();
            tableModel.addRow(item);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearTK3;
    private javax.swing.JButton btnSearchTK4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jCbb_namBD;
    private javax.swing.JComboBox<String> jCbb_namKT;
    private javax.swing.JComboBox<String> jCbb_namTao;
    private javax.swing.JComboBox<String> jCbb_ngayBD;
    private javax.swing.JComboBox<String> jCbb_ngayKT;
    private javax.swing.JComboBox<String> jCbb_ngayTao;
    private javax.swing.JComboBox<String> jCbb_thangBD;
    private javax.swing.JComboBox<String> jCbb_thangKT;
    private javax.swing.JComboBox<String> jCbb_thangTao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JTextField jTF_IDHD;
    private javax.swing.JTextField jTF_IDNV;
    private javax.swing.JTextField jTF_IDSach;
    private javax.swing.JTextField jTF_SDTKH;
    private javax.swing.JTextField jTF_SoLuong;
    private javax.swing.JTextField jTF_TimTheoMa;
    private javax.swing.JTextField jTF_TongTien;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tb_CTHD;
    private javax.swing.JTable tb_CTHD1;
    private javax.swing.JTable tb_DSHD;
    // End of variables declaration//GEN-END:variables
}
