/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import Model.DataDescriptor.NhanVien;
import Model.DataDescriptor.Sach;
import Model.InteractData.NhanVienDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ThongtinNV extends javax.swing.JPanel {

    public NhanVienDAO contrNV = new NhanVienDAO();
    public ThongtinNV() {
        initComponents();
        LayDuLieuNhanVien(contrNV.getNhanVien());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        jTF_TenNV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jR_Nam = new javax.swing.JRadioButton();
        jR_Nu = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jCbb_ngay = new javax.swing.JComboBox<>();
        jCbb_thang = new javax.swing.JComboBox<>();
        jCbb_nam = new javax.swing.JComboBox<>();
        lblDiaChi = new javax.swing.JLabel();
        jTF_DiaChi = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        jTF_SDT = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnClearTK3 = new javax.swing.JButton();
        jTF_IDNV = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblID1 = new javax.swing.JLabel();
        jTF_TimTheoMa = new javax.swing.JTextField();
        lblID2 = new javax.swing.JLabel();
        jTF_TimTheoTen = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÍ NHÂN VIÊN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblID.setText("ID nhân viên :");

        lblTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTen.setText("Tên :");

        jTF_TenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTF_TenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_TenNVActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Giới tính :");

        jR_Nam.setForeground(new java.awt.Color(51, 51, 51));
        jR_Nam.setText("Nam");

        jR_Nu.setForeground(new java.awt.Color(51, 51, 51));
        jR_Nu.setText("Nữ");
        jR_Nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR_NuActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ngày sinh :");

        jCbb_ngay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbb_ngay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jCbb_thang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbb_thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jCbb_nam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbb_nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960" }));
        jCbb_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbb_namActionPerformed(evt);
            }
        });

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDiaChi.setText("Địa chỉ :");

        jTF_DiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTF_DiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_DiaChiActionPerformed(evt);
            }
        });

        lblSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSDT.setText("SĐT :");

        jTF_SDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTF_SDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_SDTActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Thêm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/file.png"))); // NOI18N

        btnClearTK3.setBackground(new java.awt.Color(0, 255, 102));
        btnClearTK3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClearTK3.setText("Làm mới");
        btnClearTK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTK3ActionPerformed(evt);
            }
        });

        jTF_IDNV.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jR_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jR_Nu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTF_TenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(jTF_IDNV))
                        .addGap(111, 111, 111)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(lblDiaChi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jCbb_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jCbb_thang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jCbb_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTF_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTF_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnClearTK3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblID)
                                    .addComponent(jTF_IDNV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTen)
                                    .addComponent(jTF_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jR_Nam)
                                    .addComponent(jR_Nu)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCbb_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCbb_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jCbb_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSDT)
                                    .addComponent(jTF_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTF_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDiaChi))))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(btnClearTK3)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1217, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "ID nhân viên", "Tên nhân viên", "Giới tính", "Chức vụ", "Ngày sinh", "Địa chỉ", "SĐT", "Email"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));

        lblID1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblID1.setText("Tìm kiếm theo Mã:");

        jTF_TimTheoMa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTF_TimTheoMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_TimTheoMaActionPerformed(evt);
            }
        });
        jTF_TimTheoMa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTF_TimTheoMaKeyReleased(evt);
            }
        });

        lblID2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblID2.setText("Tìm kiếm theo Tên:");

        jTF_TimTheoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTF_TimTheoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTF_TimTheoTenKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblID1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTF_TimTheoMa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(lblID2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTF_TimTheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID1)
                    .addComponent(jTF_TimTheoMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID2)
                    .addComponent(jTF_TimTheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_TenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_TenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_TenNVActionPerformed

    private void jR_NuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR_NuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jR_NuActionPerformed

    private void jTF_DiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_DiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_DiaChiActionPerformed

    private void jTF_SDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_SDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_SDTActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String ID, TenNV, SDT, GioiTinh = "", NgaySinh, DiaChi;
        ID = jTF_IDNV.getText();
        TenNV = jTF_TenNV.getText();
        SDT = jTF_SDT.getText();
        if(jR_Nam.isSelected()) GioiTinh = jR_Nam.getText();
        if(jR_Nu.isSelected()) GioiTinh = jR_Nu.getText();
        String ngay, thang, nam;
        ngay = jCbb_ngay.getSelectedItem().toString();
        thang = jCbb_thang.getSelectedItem().toString();
        nam = jCbb_nam.getSelectedItem().toString();
        NgaySinh  = nam + "-" + thang + "-" + ngay;
        DiaChi = jTF_DiaChi.getText();
        
        if(!ID.equals("")){
            try {
                NhanVien a = new NhanVien( ID, TenNV, GioiTinh, NgaySinh, DiaChi, SDT);
                contrNV.deleteNhanVien(a);
                LayDuLieuNhanVien(contrNV.getNhanVien());
                
            } catch (SQLException ex) {
                Logger.getLogger(SanPhamSachc.class.getName()).log(Level.SEVERE, null, ex);
            }    
        } else{
            ThongBao("Bạn chưa chọn Nhân Viên muốn xóa", "Lỗi!", 2);
        }    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCbb_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbb_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbb_namActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String ID, TenNV, SDT, GioiTinh = "", NgaySinh, DiaChi;
        ID = jTF_IDNV.getText();
        TenNV = jTF_TenNV.getText();
        SDT = jTF_SDT.getText();
        if(jR_Nam.isSelected()) GioiTinh = jR_Nam.getText();
        if(jR_Nu.isSelected()) GioiTinh = jR_Nu.getText();
        String ngay, thang, nam;
        ngay = jCbb_ngay.getSelectedItem().toString();
        thang = jCbb_thang.getSelectedItem().toString();
        nam = jCbb_nam.getSelectedItem().toString();
        NgaySinh  = nam + "-" + thang + "-" + ngay;
        DiaChi = jTF_DiaChi.getText();
        
        if(!ID.equals("")){
            try {
                NhanVien a = new NhanVien( ID, TenNV, GioiTinh, NgaySinh, DiaChi, SDT);
                contrNV.updateNhanVien(a);
                LayDuLieuNhanVien(contrNV.getNhanVien());
                
            } catch (SQLException ex) {
                Logger.getLogger(SanPhamSachc.class.getName()).log(Level.SEVERE, null, ex);
            }    
        } else{
            ThongBao("Bạn chưa chọn Nhân Viên muốn sửa!", "Lỗi!", 2);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnClearTK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTK3ActionPerformed
        //
        ResNhanVien();
    }//GEN-LAST:event_btnClearTK3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int viTriDongVuaBam = jTable1.getSelectedRow();
        jTF_IDNV.setText(jTable1.getValueAt(viTriDongVuaBam, 1).toString());
        jTF_TenNV.setText(jTable1.getValueAt(viTriDongVuaBam, 2).toString());
        jTF_SDT.setText(jTable1.getValueAt(viTriDongVuaBam, 3).toString());
        jTF_DiaChi.setText(jTable1.getValueAt(viTriDongVuaBam, 6).toString());
        String NgaySinh = jTable1.getValueAt(viTriDongVuaBam, 5).toString();
       
        String gioitinh = jTable1.getValueAt(viTriDongVuaBam, 4).toString();
        if (gioitinh.equals("Nữ")) {
            jR_Nu.setSelected(true);
            jR_Nam.setSelected(false);
        }
        else {
            jR_Nam.setSelected(true);
            jR_Nu.setSelected(false);
        }
        
        System.out.println(NgaySinh);
        String s_nam = "";
        String s_thang = "" + NgaySinh.charAt(5) + NgaySinh.charAt(6);
        String s_ngay = "" + NgaySinh.charAt(8) + NgaySinh.charAt(9);
        for (int i=0; i<4; i++){
            s_nam += NgaySinh.charAt(i);
        }
        System.out.println(s_ngay);
        System.out.println(s_nam);
        System.out.println(s_thang);
        setSelectedCombobox(String.valueOf(s_ngay), jCbb_ngay);
        setSelectedCombobox(String.valueOf(s_thang), jCbb_thang);
        setSelectedCombobox(String.valueOf(s_nam), jCbb_nam);

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTF_TimTheoMaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_TimTheoMaKeyReleased
        // TODO add your handling code here:
        LayDuLieuNhanVien(contrNV.getNhanVienTheoMa(jTF_TimTheoMa.getText()));
    }//GEN-LAST:event_jTF_TimTheoMaKeyReleased

    private void jTF_TimTheoTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_TimTheoTenKeyReleased
        // TODO add your handling code here:
        LayDuLieuNhanVien(contrNV.getNhanVienTheoTen(jTF_TimTheoTen.getText()));
    }//GEN-LAST:event_jTF_TimTheoTenKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String ID = "", TenNV, SDT, GioiTinh = "", NgaySinh, DiaChi;
        TenNV = jTF_TenNV.getText();
        SDT = jTF_SDT.getText();
        if(jR_Nam.isSelected()) GioiTinh = jR_Nam.getText();
        if(jR_Nu.isSelected()) GioiTinh = jR_Nu.getText();
        String ngay, thang, nam;
        ngay = jCbb_ngay.getSelectedItem().toString();
        thang = jCbb_thang.getSelectedItem().toString();
        nam = jCbb_nam.getSelectedItem().toString();
        NgaySinh  = nam + "-" + thang + "-" + ngay;
        DiaChi = jTF_DiaChi.getText();
        
        NhanVien a = new NhanVien( ID, TenNV, GioiTinh, NgaySinh, DiaChi, SDT);
        System.out.println("tạo nhân viên mới");
        try {
            System.out.println("chuẩn bị thêm");
            contrNV.addNhanVien(a);
            LayDuLieuNhanVien(contrNV.getNhanVien());
        } catch (SQLException ex) {
            Logger.getLogger(ThongtinNV.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTF_TimTheoMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_TimTheoMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_TimTheoMaActionPerformed

    public void ResNhanVien() {
        jTF_IDNV.setText("");
        jTF_TenNV.setText("");
        jTF_SDT.setText("");
        jTF_DiaChi.setText("");
        jR_Nu.setSelected(false);
        jR_Nam.setSelected(false);
    }
    
    public void setSelectedCombobox(String cbbselected, JComboBox cbb) {
        int so = Integer.parseInt(cbbselected);
        cbbselected = String.valueOf(so);   
        for (int i = 0; i < cbb.getItemCount(); i++) {
            String obj = String.valueOf(cbb.getItemAt(i));
            if (obj != null) {
                if (cbbselected.trim().equals(obj)) {
                    cbb.setSelectedItem(obj);
                }
            }
        }
    }
    
    public void ThongBao(String noiDungThongBao, String tieuDeThongBao, int icon) {
        JOptionPane.showMessageDialog(new JFrame(), noiDungThongBao,
                tieuDeThongBao, icon);
    }
    
    public void LayDuLieuNhanVien(ArrayList<NhanVien> listNv) {
        Object[] obj = new Object[]{"STT", "ID_NV", "Họ tên", "SDT", "Giới tính", "Ngày sinh", "Địa chỉ"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        jTable1.setModel(tableModel);
        int c = 0;
        for (NhanVien x :listNv){
            Object[] item = new Object[9];
                c++;
                item[0] = c;
                item[1] = x.getID_NV();
                item[2] = x.getTen();
                item[3] = x.getSDt();
                item[4] = x.getGioiTinh();
                item[5] = x.getNgaySinh();
                item[6] = x.getDiaChi();
                tableModel.addRow(item);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearTK3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCbb_nam;
    private javax.swing.JComboBox<String> jCbb_ngay;
    private javax.swing.JComboBox<String> jCbb_thang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jR_Nam;
    private javax.swing.JRadioButton jR_Nu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_DiaChi;
    private javax.swing.JTextField jTF_IDNV;
    private javax.swing.JTextField jTF_SDT;
    private javax.swing.JTextField jTF_TenNV;
    private javax.swing.JTextField jTF_TimTheoMa;
    private javax.swing.JTextField jTF_TimTheoTen;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblID2;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTen;
    // End of variables declaration//GEN-END:variables
}
