/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import Model.DataDescriptor.KhachHang;
import Model.InteractData.KhachHangDAO;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Admin
 */
public class thongtinKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form thongtinKhachHang
     */
    private KhachHangDAO contrKH = new KhachHangDAO();
    public thongtinKhachHang() {
        initComponents();
        LayDuLieuKhachHang(contrKH.getKhachHang());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTF_TimTheoSDT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTF_TimTheoTen = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblIDKH = new javax.swing.JLabel();
        lblTenKH = new javax.swing.JLabel();
        jTF_TenKH = new javax.swing.JTextField();
        lblGioiTinh = new javax.swing.JLabel();
        jR_Nam = new javax.swing.JRadioButton();
        jR_Nu = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jCbb_ngay = new javax.swing.JComboBox<>();
        jCbb_thang = new javax.swing.JComboBox<>();
        jCbb_nam = new javax.swing.JComboBox<>();
        lblDiaChi = new javax.swing.JLabel();
        jTF_Email = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        jTF_DiaChi = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        jTF_SDT = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnClearTK3 = new javax.swing.JButton();
        jTF_IDKH = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THÔNG TIN KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel5.setForeground(new java.awt.Color(204, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "ID KH", "Tên KH", "Giới tính", "Ngày sinh", "Địa chỉ", "Email"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTF_TimTheoSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTF_TimTheoSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_TimTheoSDTActionPerformed(evt);
            }
        });
        jTF_TimTheoSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTF_TimTheoSDTKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Tìm kiếm theo SDT:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Tìm kiếm theo Tên:");

        jTF_TimTheoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTF_TimTheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_TimTheoTenActionPerformed(evt);
            }
        });
        jTF_TimTheoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTF_TimTheoTenKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTF_TimTheoSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jTF_TimTheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTF_TimTheoSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTF_TimTheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));

        lblIDKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIDKH.setText("ID Khách hàng :");

        lblTenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTenKH.setText("Tên :");

        jTF_TenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTF_TenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_TenKHActionPerformed(evt);
            }
        });

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGioiTinh.setText("Giới tính :");

        jR_Nam.setForeground(new java.awt.Color(51, 51, 51));
        jR_Nam.setText("Nam");

        jR_Nu.setForeground(new java.awt.Color(51, 51, 51));
        jR_Nu.setText("Nữ");
        jR_Nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR_NuActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ngày sinh :");

        jCbb_ngay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbb_ngay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jCbb_thang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbb_thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jCbb_nam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbb_nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960" }));
        jCbb_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbb_namActionPerformed(evt);
            }
        });

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDiaChi.setText("Địa chỉ :");

        jTF_Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTF_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_EmailActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setText("Email :");

        jTF_DiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTF_DiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_DiaChiActionPerformed(evt);
            }
        });

        lblSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSDT.setText("SĐT :");

        jTF_SDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTF_SDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_SDTActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Thêm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/file.png"))); // NOI18N

        btnClearTK3.setBackground(new java.awt.Color(0, 255, 102));
        btnClearTK3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClearTK3.setText("Làm mới");
        btnClearTK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTK3ActionPerformed(evt);
            }
        });

        jTF_IDKH.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIDKH, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jR_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jR_Nu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTF_IDKH, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTF_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(lblEmail)
                                            .addGap(9, 9, 9))
                                        .addComponent(lblDiaChi, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTF_SDT)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jCbb_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCbb_thang, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCbb_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTF_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTF_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btnClearTK3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCbb_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbb_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jCbb_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(jTF_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiaChi)
                            .addComponent(jTF_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSDT)
                            .addComponent(jTF_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDKH)
                            .addComponent(jTF_IDKH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenKH)
                            .addComponent(jTF_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGioiTinh)
                            .addComponent(jR_Nam)
                            .addComponent(jR_Nu))
                        .addGap(62, 62, 62))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(btnClearTK3))
                .addGap(112, 112, 112)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(125, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(662, 662, 662))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(133, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_TenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_TenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_TenKHActionPerformed

    private void jR_NuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR_NuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jR_NuActionPerformed

    private void jCbb_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbb_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbb_namActionPerformed

    private void jTF_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_EmailActionPerformed

    private void jTF_DiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_DiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_DiaChiActionPerformed

    private void jTF_SDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_SDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_SDTActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String ID, ten, ngaySinh, gioiTinh, diaChi, email, SDT;
        ID = jTF_IDKH.getText();;
        ten = jTF_TenKH.getText();
        diaChi = jTF_DiaChi.getText();
        email = jTF_Email.getText();
        SDT = jTF_SDT.getText();
        
        if(jR_Nam.isSelected()) gioiTinh = jR_Nam.getText();
        else gioiTinh = jR_Nu.getText();
        
        String ngay, thang, nam;
        ngay = jCbb_ngay.getSelectedItem().toString();
        thang = jCbb_thang.getSelectedItem().toString();
        nam = jCbb_nam.getSelectedItem().toString();
        ngaySinh  = nam + "-" + thang + "-" + ngay;
        if(!ID.equals("")){
            try {
                KhachHang a = new KhachHang(ID, ten, gioiTinh, ngaySinh, diaChi, SDT, email);
                contrKH.updateKhachHang(a);
                LayDuLieuKhachHang(contrKH.getKhachHang());           
            } catch (SQLException ex) {
                Logger.getLogger(SanPhamSachc.class.getName()).log(Level.SEVERE, null, ex);
            }    
        } else{
            ThongBao("Bạn chưa chọn Khách Hàng muốn sửa!", "Lỗi!", 2);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String ID, ten, ngaySinh, gioiTinh, diaChi, email, SDT;
        ID = jTF_IDKH.getText();;
        ten = jTF_TenKH.getText();
        diaChi = jTF_DiaChi.getText();
        email = jTF_Email.getText();
        SDT = jTF_SDT.getText();
        
        if(jR_Nam.isSelected()) gioiTinh = jR_Nam.getText();
        else gioiTinh = jR_Nu.getText();
        
        String ngay, thang, nam;
        ngay = jCbb_ngay.getSelectedItem().toString();
        thang = jCbb_thang.getSelectedItem().toString();
        nam = jCbb_nam.getSelectedItem().toString();
        ngaySinh  = nam + "-" + thang + "-" + ngay;
        if(!ID.equals("")){
            try {
                KhachHang a = new KhachHang(ID, ten, gioiTinh, ngaySinh, diaChi, SDT, email);
                contrKH.deleteKhachHang(a);
                LayDuLieuKhachHang(contrKH.getKhachHang());           
            } catch (SQLException ex) {
                Logger.getLogger(SanPhamSachc.class.getName()).log(Level.SEVERE, null, ex);
            }    
        } else{
            ThongBao("Bạn chưa chọn Khách Hàng muốn xóa", "Lỗi!", 2);
        }

        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnClearTK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTK3ActionPerformed
        //
        ResKhachHang();
    }//GEN-LAST:event_btnClearTK3ActionPerformed

    private void jTF_TimTheoSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_TimTheoSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_TimTheoSDTActionPerformed

    private void jTF_TimTheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_TimTheoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_TimTheoTenActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int viTriDongVuaBam = jTable1.getSelectedRow();
        jTF_IDKH.setText(jTable1.getValueAt(viTriDongVuaBam, 1).toString());
        jTF_TenKH.setText(jTable1.getValueAt(viTriDongVuaBam, 2).toString());
        jTF_SDT.setText(jTable1.getValueAt(viTriDongVuaBam, 3).toString());
        jTF_DiaChi.setText(jTable1.getValueAt(viTriDongVuaBam, 6).toString());
        jTF_Email.setText(jTable1.getValueAt(viTriDongVuaBam, 7).toString());
        String NgaySinh = jTable1.getValueAt(viTriDongVuaBam, 5).toString();
        String gioitinh = jTable1.getValueAt(viTriDongVuaBam, 4).toString();
        if (gioitinh.equals("Nữ")) {
            jR_Nu.setSelected(true);
            jR_Nam.setSelected(false);
        }
        else {
            jR_Nam.setSelected(true);
            jR_Nu.setSelected(false);
        }
        
        System.out.println(NgaySinh);
        String s_nam = "";
        String s_thang = "" + NgaySinh.charAt(5) + NgaySinh.charAt(6);
        String s_ngay = "" + NgaySinh.charAt(8) + NgaySinh.charAt(9);
        for (int i=0; i<4; i++){
            s_nam += NgaySinh.charAt(i);
        }
        
        setSelectedCombobox(String.valueOf(s_ngay), jCbb_ngay);
        setSelectedCombobox(String.valueOf(s_thang), jCbb_thang);
        setSelectedCombobox(String.valueOf(s_nam), jCbb_nam);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTF_TimTheoSDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_TimTheoSDTKeyReleased
        // TODO add your handling code here:
        LayDuLieuKhachHang(contrKH.getKhachHangTheoSDT(jTF_TimTheoSDT.getText()));
    }//GEN-LAST:event_jTF_TimTheoSDTKeyReleased

    private void jTF_TimTheoTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_TimTheoTenKeyReleased
        // TODO add your handling code here:
        LayDuLieuKhachHang(contrKH.getKhachHangTheoTen(jTF_TimTheoTen.getText()));
    }//GEN-LAST:event_jTF_TimTheoTenKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:   
        String ID, ten, ngaySinh, gioiTinh, diaChi, email, SDT;
        ID = "";
        ten = jTF_TenKH.getText();
        diaChi = jTF_DiaChi.getText();
        email = jTF_Email.getText();
        SDT = jTF_SDT.getText();
        
        if(jR_Nam.isSelected()) gioiTinh = jR_Nam.getText();
        else gioiTinh = jR_Nu.getText();
        
        String ngay, thang, nam;
        ngay = jCbb_ngay.getSelectedItem().toString();
        thang = jCbb_thang.getSelectedItem().toString();
        nam = jCbb_nam.getSelectedItem().toString();
        ngaySinh  = nam + "-" + thang + "-" + ngay;
        
        KhachHang a = new KhachHang(ID, ten, gioiTinh, ngaySinh, diaChi, SDT, email);
        boolean kiemtra = KiemTraNhapKhachHang(0);
        if (kiemtra) {
            try {
                contrKH.addKhachHang(a);
                System.out.println("Thành công");
                //ThongBao("Đã Thêm Thành Công", "", 1);
            } catch (SQLException ex) {
                Logger.getLogger(thongtinKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("Thất bại");
        }
        LayDuLieuKhachHang(contrKH.getKhachHang());
        
    }//GEN-LAST:event_jButton4ActionPerformed

    public boolean KiemTraNhapKhachHang(int ts) {
        boolean kiemtra;
        String ID, ten, ngaySinh, gioiTinh, diaChi, email, SDT, ThongBao="";
        ID = "";
        ten = jTF_TenKH.getText();
        diaChi = jTF_DiaChi.getText();
        email = jTF_Email.getText();
        SDT = jTF_SDT.getText();
        
        if(jR_Nam.isSelected()) gioiTinh = jR_Nam.getText();
        else gioiTinh = jR_Nu.getText();
        
        String ngay, thang, nam;
        ngay = jCbb_ngay.getSelectedItem().toString();
        thang = jCbb_thang.getSelectedItem().toString();
        nam = jCbb_nam.getSelectedItem().toString();
        ngaySinh  = nam + "-" + thang + "-" + ngay;
        KhachHang a = new KhachHang(ID, ten, gioiTinh, ngaySinh, diaChi, email, SDT);
        if (a.getTen().equals("")) {
            ThongBao += "Bạn chưa nhập tên Khách hàng!\n";
            lblTenKH.setForeground(Color.red);
        }
        if (a.getDiaChi().equals("")) {
            ThongBao += "Bạn chưa nhập Địa chỉ!\n";
            lblDiaChi.setForeground(Color.red);
        }
        System.out.println(a.getSDT());
        if(!checkSDT(a.getSDT())){
            ThongBao += "Số điện thoại không hợp lệ!\n"; 
            lblSDT.setForeground(Color.red);
        }
        if (a.getEmail().equals("")) {
            ThongBao += "Bạn chưa nhập Email!\n";
            lblEmail.setForeground(Color.red);
        }
        if(contrKH.kiemTraKH(a)){
            ThongBao += "Khách hàng đã được thêm vào trước đó!\n";
        }
        
        if (ThongBao.equals("")) {
            kiemtra = true;
            lblTenKH.setForeground(Color.black);
            lblDiaChi.setForeground(Color.black);
            lblEmail.setForeground(Color.black);
            lblSDT.setForeground(Color.black);
        } else {
            kiemtra = false;
            ThongBao(ThongBao, "Lỗi nhập liệu", 2);
        }
        return kiemtra;
    }
    
    public void ResKhachHang() {
        jTF_IDKH.setText("");
        jTF_TenKH.setText("");
        jTF_SDT.setText("");
        jTF_DiaChi.setText("");
        jTF_Email.setText("");
        jR_Nu.setSelected(false);
        jR_Nam.setSelected(false);
   
    }
    
    private boolean checkSDT(String s){
        s = s.trim();
        for(int i=0; i<s.length(); i++){
            if(s.charAt(i) < '0' || s.charAt(i) > '9'){             
                System.out.println(s.charAt(i));
                return false;
            }
        }
        return true;
    }
    
    public void ThongBao(String noiDungThongBao, String tieuDeThongBao, int icon) {
        JOptionPane.showMessageDialog(new JFrame(), noiDungThongBao,
                tieuDeThongBao, icon);
    }
    
    public void setSelectedCombobox(String cbbselected, JComboBox cbb) {
        int so = Integer.parseInt(cbbselected);
        cbbselected = String.valueOf(so);   
        for (int i = 0; i < cbb.getItemCount(); i++) {
            String obj = String.valueOf(cbb.getItemAt(i));
            if (obj != null) {
                if (cbbselected.trim().equals(obj)) {
                    cbb.setSelectedItem(obj);
                }
            }
        }
    }
    
    public void LayDuLieuKhachHang(ArrayList<KhachHang> listKH) {
        Object[] obj = new Object[]{"STT", "ID KH", "Họ tên", "SDT", "Giới Tính", "Ngày Sinh", "Địa Chỉ", "Email"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        jTable1.setModel(tableModel);
        int c = 0;
        for (KhachHang x : listKH){
            Object[] item = new Object[9];
                c++;
                item[0] = c;
                item[1] = x.getID_KH();
                item[2] = x.getTen();
                item[3] = x.getSDT();
                item[4] = x.getGioiTinh();
                item[5] = x.getNgaySinh();
                item[6] = x.getDiaChi();
                item[7] = x.getEmail();
                tableModel.addRow(item);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearTK3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCbb_nam;
    private javax.swing.JComboBox<String> jCbb_ngay;
    private javax.swing.JComboBox<String> jCbb_thang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jR_Nam;
    private javax.swing.JRadioButton jR_Nu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_DiaChi;
    private javax.swing.JTextField jTF_Email;
    private javax.swing.JTextField jTF_IDKH;
    private javax.swing.JTextField jTF_SDT;
    private javax.swing.JTextField jTF_TenKH;
    private javax.swing.JTextField jTF_TimTheoSDT;
    private javax.swing.JTextField jTF_TimTheoTen;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblIDKH;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTenKH;
    // End of variables declaration//GEN-END:variables
}
